### ISSUE TITLE
how to refresh token?

### ISSUE THREAD

**Issue by janreyho** [pyeve/flask-sentinel#20]
is there a curl example to use "refresh_token" to refresh token?

**Comment by janreyho** [comment]
modify flask_sentinel/models.py
```
class Client(BaseModel):
    def allowed_grant_types(self):
-        return ['password']
+        return ['password','refresh_token']
```

then fresh token:
`https://localhost:5000/oauth/token?client_id=STmAq9vcrESf5pLcqcCaHvEr65Z6MDyJInbaVSQg&grant_type=refresh_token&refresh_token=nrLXvkXJcvQRollGOjPe1yiNtIWUVz `

**Comment by nicolaiarocci** [comment]
Excellent. Would you be willing to submit a PR which also includes a README update?

**Comment by janreyho** [comment]
YES, very happy to do it, but:
```
➜  flask-sentinel git:(develop) git push
remote: Permission to nicolaiarocci/flask-sentinel.git denied to janreyho.
fatal: unable to access 'https://github.com/nicolaiarocci/flask-sentinel.git/': The requested URL returned error: 403
```

**Comment by nicolaiarocci** [comment]
You first need to fork the repository. See https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by janreyho** [comment]
I have already forked the repository on Aug 14, 2016. [https://github.com/janreyho/flask-sentinel](https://github.com/janreyho/flask-sentinel)
> Would you be willing to submit a PR which also includes a README update?

This sentence I understand, you want me to push a update to your repository, but I don't have  that right.
